services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  
    entrypoint: ["/app/entrypoint.sh"] 
    command: gunicorn --bind 0.0.0.0:8000 --config /app/gunicorn.conf.py config.wsgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    expose:
      - "8000"

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - web

